#!/bin/sh
#export TZ="$1"/"$2"
#date

#RR=$(date)
#zenity --info --text="$RR"
GETTEXT="gettext -d codefile"

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog 
end () { 
exit 
} 
while true 
do
 $DIALOG --inputbox "`$GETTEXT \"Please select your timezone by entering Continent/City\"`" 8 50 2>/tmp/input.$$ 
export TZ=`cat /tmp/input.$$` 
MSG="The time and date for your selescted timezone are:\n\n `date` \n\nNew Search?" 
$DIALOG --yesno "$MSG" 8 50 || end 
done

