#!/bin/sh
#export TZ="$1"/"$2"
#date

#RR=$(date)
#zenity --info --text="$RR"
GETTEXT="gettext -d codefile"

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog 
end () { 
exit 
} 
while true 
do
 $DIALOG --inputbox "`$GETTEXT \"Please select your timezone by entering Continent/City\"`" 8 50 2>/tmp/input.$$ 
export TZ=`cat /tmp/input.$$` 
MSG="`$GETTEXT \"The date and time in your selected timezone are:\"`\n\n`date` \n\n`$GETTEXT \"New Search?\"`"
#MSG="The time and date for your selected timezone are:\n\n `date` \n\nNew Search?"
#MSG="`$GETTEXT \"The time and date for your selected timezone are:\"`" \n\n `date` \n\n "`$GETTEXT \"New Search?\"`"
$DIALOG --yesno "$MSG" 8 50 || end 
done

